version: '3.8'

services:
  tododb:
    image: mariadb:latest
    container_name: tododb
    environment:
      MARIADB_USER: yehtetaung
      MARIADB_PASSWORD: tododb
      MARIADB_DATABASE: todolist
      MARIADB_ROOT_PASSWORD: Rootsystem32
    networks:
      - todoapp
    restart: always

  todo-api:
    image: dckre20058568/todo-api:latest
    container_name: todo-api
    ports:
      - "8000:8000"
    environment:
      DB_USER: yehtetaung
      DB_PASS: tododb
      DB_HOST: tododb
      DB_PORT: 3306
      DB_NAME: todolist
    networks:
      - todoapp
    depends_on:
      - tododb
    restart: always

  todo-front:
    image: dckre20058568/todo-front:latest
    container_name: todo-front
    ports:
      - "8080:80"
    environment:
      TODO_API_HOST: "172.17.0.1"
      TODO_API_PORT: "8000"
    networks:
      - todoapp
    restart: always

networks:
  todoapp:
    driver: bridge
