version: '3.8'

services:
  tododb:
    image: mariadb:latest
    container_name: tododb
    environment:
      MARIADB_USER: yehtetaung
      MARIADB_PASSWORD: tododb
      MARIADB_DATABASE: todolist
      MARIADB_ROOT_PASSWORD: Rootsystem32
    networks:
      - todoapp
    restart: always

  todo-api:
    image: todo-api
    container_name: todo-api
    ports:
      - "8000:8000"
    environment:
      DB_USER: yehtetaung
      DB_PASS: tododb
      DB_HOST: tododb
      DB_PORT: 3306
      DB_NAME: todolist
    networks:
      - todoapp
    depends_on:
      - tododb
    restart: always

networks:
  todoapp:
    driver: bridge

