name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build images
        run: |
          docker build -t dckre20058568/todo-api:latest ./todoapi/
          docker build -t dckre20058568/todo-front:latest ./todofront/

      - name: Push images to Docker Hub
        run: |
          docker push dckre20058568/todo-api:latest
          docker push dckre20058568/todo-front:latest

